const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const api=async(path,opts={})=>{const r=await fetch(path,opts),j=await r.json();if(!r.ok)throw Error(j.error||'Request failed');return j};
const post=(path,data)=>api(path,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(data)});
let state={rooms:[],edges:[],videos:[]}, selected=null, drag=null, activeJob=null;
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const media=p=>p?'/media/'+encodeURI(p.replace(/^.*OSFR-Dungeon-Mapper\//,'')):'';
function msg(x){$('#message').textContent=typeof x==='string'?x:JSON.stringify(x,null,2)}

async function load(){const ds=await api('/api/dungeons');$('#dungeon').innerHTML=ds.map(d=>`<option>${esc(d.name)}</option>`).join('');await refresh();setInterval(pollJobs,1500)}
async function refresh(){state=await api('/api/graph?dungeon='+encodeURIComponent($('#dungeon').value));$('#title').textContent=state.dungeon.name;$('#stats').textContent=`${state.rooms.filter(r=>r.status!=='rejected').length} rooms • ${state.edges.length} consensus connections • ${state.videos.length} videos`;
 const ready=state.videos.filter(v=>v.path), options=ready.map(v=>`<option value="${v.id}">${esc(v.title)} (${v.status})</option>`).join('');$('#video').innerHTML='<option value="">Select a ready video</option>'+options;$('#reviewVideo').innerHTML='<option value="">Choose video</option>'+options;
 const floors=[...new Set(state.rooms.map(r=>r.floor||1))].sort((a,b)=>a-b);$('#floor').innerHTML='<option value="all">All</option>'+floors.map(f=>`<option value="${f}">${f}</option>`).join('');draw();drawEdges();if(selected){selected=state.rooms.find(r=>r.id===selected.id)||null;showSelected()}}

function visibleRooms(){const f=$('#floor').value;return state.rooms.filter(r=>r.status!=='rejected'&&(f==='all'||String(r.floor||1)===f))}
function draw(){const svg=$('#graph'),rooms=visibleRooms(),pos={};rooms.forEach((n,i)=>{if(n.x==null)n.x=600+Math.cos(i*2.399)*250;if(n.y==null)n.y=350+Math.sin(i*2.399)*250;pos[n.id]=[n.x,n.y]});let out='';state.edges.filter(e=>pos[e.from_room]&&pos[e.to_room]).forEach(e=>{const a=pos[e.from_room],b=pos[e.to_room],col=e.status==='confirmed'?'#63e6a5':'#547068';out+=`<line x1="${a[0]}" y1="${a[1]}" x2="${b[0]}" y2="${b[1]}" stroke="${col}" opacity="${Math.max(.35,e.confidence)}"/>`});rooms.forEach(n=>{const p=pos[n.id],col=n.status==='confirmed'?'#63e6a5':'#f5bd65';out+=`<g class="node" data-id="${n.id}" transform="translate(${p[0]} ${p[1]})"><circle r="43" fill="#14201e" stroke="${col}"/><text y="1">${esc(n.label).slice(0,19)}</text><text class="sub" y="17">F${n.floor||1} • ${n.kind||'room'}</text></g>`});svg.innerHTML=out}
function drawEdges(){$('#edges').innerHTML=state.edges.length?state.edges.map(e=>`<div class="edge"><span>${esc(e.from_label)} → ${esc(e.to_label)}</span><span>${e.supporting_videos} video${e.supporting_videos===1?'':'s'}</span><div><small>${Math.round(e.confidence*100)}%</small><div class="meter"><i style="width:${e.confidence*100}%"></i></div></div><div class="actions"><button class="muted" data-edge="${e.from_room},${e.to_room}" data-status="confirmed">Confirm</button><button class="danger" data-edge="${e.from_room},${e.to_room}" data-status="rejected">Reject</button></div></div>`).join(''):'<span class="empty">No transitions analyzed yet.</span>'}

function showSelected(){const box=$('#selected');if(!selected){box.className='selected empty';box.textContent='Select a room on the graph.';return}box.className='selected';const evidence=(selected.evidence||[]).slice(0,9);box.innerHTML=`<div class="fieldrow"><input id="roomLabel" value="${esc(selected.label)}"><input id="roomFloor" type="number" min="1" value="${selected.floor||1}"></div><select id="roomKind"><option>room</option><option>entrance</option><option>combat</option><option>puzzle</option><option>boss</option><option>treasure</option><option>stairs</option><option>portal</option></select><textarea id="roomNotes" placeholder="Landmarks, enemies, objectives…">${esc(selected.notes||'')}</textarea><div class="thumbs">${evidence.map(e=>`<img src="${media(e.frame_path)}" title="${esc(e.video_title)} @ ${e.timestamp}s" data-video="${e.video_id}" data-time="${e.timestamp}">`).join('')}</div><small>${selected.evidence.length} observations</small><div class="actions"><button data-room-action="confirm">Confirm</button><button class="muted" data-room-action="save">Save</button><button class="danger" data-room-action="reject">Reject</button></div><label>Merge into</label><select id="mergeTarget"><option value="">Choose room…</option>${state.rooms.filter(r=>r.id!==selected.id&&r.status!=='rejected').map(r=>`<option value="${r.id}">${esc(r.label)}</option>`).join('')}</select><button class="secondary" data-room-action="merge">Merge duplicate</button>`;$('#roomKind').value=selected.kind||'room'}
function playEvidence(video,time){$('#reviewVideo').value=video;setVideo(video);$('#player').currentTime=Number(time);$('#player').play().catch(()=>{})}
function setVideo(id){$('#player').src=id?'/api/video?id='+id:''}

$('#dungeon').onchange=()=>{selected=null;refresh()};$('#floor').onchange=draw;$('#reviewVideo').onchange=e=>setVideo(e.target.value);
$$('[data-seek]').forEach(b=>b.onclick=()=>$('#player').currentTime=Math.max(0,$('#player').currentTime+Number(b.dataset.seek)));
$$('.tab').forEach(b=>b.onclick=()=>{$$('.tab').forEach(x=>x.classList.toggle('active',x===b));$$('[data-panel]').forEach(p=>p.hidden=p.dataset.panel!==b.dataset.tab)});
$('#import').onclick=async()=>{msg('Importing metadata…');try{msg(await post('/api/import',{dungeon:$('#dungeon').value}))}catch(e){msg(e.message)}await refresh()};
$('#download').onclick=async()=>{msg('Downloading playlist…');try{msg(await post('/api/import',{dungeon:$('#dungeon').value,download:true}))}catch(e){msg(e.message)}await refresh()};
$('#add').onclick=async()=>{try{msg(await post('/api/local-video',{dungeon:$('#dungeon').value,path:$('#path').value}))}catch(e){msg(e.message)}await refresh()};
$('#analyze').onclick=async()=>{if(!$('#video').value)return msg('Choose a video first.');try{const r=await post('/api/analyze',{video_id:$('#video').value,interval:$('#interval').value});activeJob=r.job_id;msg(`Analysis queued: ${activeJob}`)}catch(e){msg(e.message)}};
async function pollJobs(){try{const jobs=await api('/api/jobs'),job=jobs.find(j=>j.id===activeJob)||jobs.at(-1);if(!job)return;$('#job').textContent=job.status.toUpperCase();if(job.id===activeJob&&(job.status==='complete'||job.status==='failed')){msg(job);activeJob=null;await refresh()}}catch{}}

$('#graph').addEventListener('pointerdown',e=>{const n=e.target.closest('.node');if(!n)return;const room=state.rooms.find(r=>r.id===Number(n.dataset.id));selected=room;showSelected();const pt=$('#graph').createSVGPoint();pt.x=e.clientX;pt.y=e.clientY;const start=pt.matrixTransform($('#graph').getScreenCTM().inverse());drag={room,node:n,dx:start.x-(room.x??0),dy:start.y-(room.y??0)};n.setPointerCapture(e.pointerId)});
$('#graph').addEventListener('pointermove',e=>{if(!drag)return;const pt=$('#graph').createSVGPoint();pt.x=e.clientX;pt.y=e.clientY;const p=pt.matrixTransform($('#graph').getScreenCTM().inverse());drag.room.x=p.x-drag.dx;drag.room.y=p.y-drag.dy;drag.node.setAttribute('transform',`translate(${drag.room.x} ${drag.room.y})`)});
$('#graph').addEventListener('pointerup',async()=>{if(!drag)return;await post('/api/review',{room_id:drag.room.id,x:drag.room.x,y:drag.room.y});drag=null;draw()});
$('#selected').onclick=async e=>{if(e.target.matches('img'))return playEvidence(e.target.dataset.video,e.target.dataset.time);const action=e.target.dataset.roomAction;if(!action||!selected)return;if(action==='merge'){const target=$('#mergeTarget').value;if(target)await post('/api/merge',{source_id:selected.id,target_id:target});selected=null}else{const status=action==='confirm'?'confirmed':action==='reject'?'rejected':selected.status;await post('/api/review',{room_id:selected.id,status,label:$('#roomLabel').value,floor:Number($('#roomFloor').value),kind:$('#roomKind').value,notes:$('#roomNotes').value})}await refresh()};
$('#edges').onclick=async e=>{if(!e.target.dataset.edge)return;const [from,to]=e.target.dataset.edge.split(',');await post('/api/transition',{dungeon:$('#dungeon').value,from_room:from,to_room:to,status:e.target.dataset.status});await refresh()};
for(const [id,format] of [['export','json'],['dot','dot'],['csv','csv']])$('#'+id).onclick=async()=>msg(await post('/api/export',{dungeon:$('#dungeon').value,format}));
load().catch(e=>msg(e.message));
