const $=s=>document.querySelector(s), api=async(path,opts={})=>{const r=await fetch(path,opts);const j=await r.json();if(!r.ok)throw Error(j.error||'Request failed');return j};
let state={rooms:[],edges:[],videos:[]};
function post(path,data){return api(path,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(data)})}
function msg(x){$('#message').textContent=typeof x==='string'?x:JSON.stringify(x,null,2)}
async function load(){const ds=await api('/api/dungeons');$('#dungeon').innerHTML=ds.map(d=>`<option>${d.name}</option>`).join('');await refresh()}
async function refresh(){state=await api('/api/graph?dungeon='+encodeURIComponent($('#dungeon').value));$('#title').textContent=state.dungeon.name;$('#stats').textContent=`${state.rooms.length} rooms • ${state.edges.length} observed transitions • ${state.videos.length} videos`;$('#video').innerHTML='<option value="">Select a ready video</option>'+state.videos.filter(v=>v.path).map(v=>`<option value="${v.id}">${v.title} (${v.status})</option>`).join('');draw();review()}
function draw(){const svg=$('#graph'),rooms=state.rooms.filter(r=>r.status!=='rejected'),w=1200,h=700,cx=w/2,cy=h/2,r=Math.min(270,55+rooms.length*12),pos={};rooms.forEach((n,i)=>{const a=(i/Math.max(rooms.length,1))*Math.PI*2-Math.PI/2;pos[n.id]=[cx+Math.cos(a)*r,cy+Math.sin(a)*r]});let out='';state.edges.filter(e=>pos[e.from_room]&&pos[e.to_room]).forEach(e=>{const a=pos[e.from_room],b=pos[e.to_room];out+=`<line x1="${a[0]}" y1="${a[1]}" x2="${b[0]}" y2="${b[1]}"/>`});rooms.forEach(n=>{const p=pos[n.id],col=n.status==='confirmed'?'#63e6a5':'#f5bd65';out+=`<g class="node"><circle cx="${p[0]}" cy="${p[1]}" r="36" fill="#14201e" stroke="${col}"/><text x="${p[0]}" y="${p[1]+4}">${esc(n.label).slice(0,20)}</text></g>`});svg.innerHTML=out}
function esc(s){return String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function review(){$('#rooms').innerHTML=state.rooms.filter(r=>r.status!=='rejected').map(r=>`<article class="room"><img src="${r.representative_frame?'/media/'+encodeURI(r.representative_frame.replace(/^.*OSFR-Dungeon-Mapper\//,'')):''}"><input value="${esc(r.label)}" data-label="${r.id}"><div class="actions"><button data-confirm="${r.id}">${r.status==='confirmed'?'Confirmed ✓':'Confirm'}</button><button class="reject" data-reject="${r.id}">Reject</button></div></article>`).join('')}
$('#dungeon').onchange=refresh;
$('#import').onclick=async()=>{msg('Importing playlist metadata…');try{msg(await post('/api/import',{dungeon:$('#dungeon').value}))}catch(e){msg(e.message)}await refresh()};
$('#download').onclick=async()=>{msg('Downloading playlist. This can take a while…');try{msg(await post('/api/import',{dungeon:$('#dungeon').value,download:true}))}catch(e){msg(e.message)}await refresh()};
$('#add').onclick=async()=>{try{msg(await post('/api/local-video',{dungeon:$('#dungeon').value,path:$('#path').value}))}catch(e){msg(e.message)}await refresh()};
$('#analyze').onclick=async()=>{if(!$('#video').value)return msg('Choose a video first.');msg('Analyzing frames and transitions…');try{msg(await post('/api/analyze',{video_id:$('#video').value,interval:$('#interval').value}))}catch(e){msg(e.message)}await refresh()};
$('#rooms').onclick=async e=>{const id=e.target.dataset.confirm||e.target.dataset.reject;if(!id)return;await post('/api/review',{room_id:id,status:e.target.dataset.confirm?'confirmed':'rejected'});await refresh()};
$('#rooms').onchange=async e=>{if(!e.target.dataset.label)return;await post('/api/review',{room_id:e.target.dataset.label,label:e.target.value});await refresh()};
$('#export').onclick=async()=>msg(await post('/api/export',{dungeon:$('#dungeon').value,format:'json'}));$('#dot').onclick=async()=>msg(await post('/api/export',{dungeon:$('#dungeon').value,format:'dot'}));load().catch(e=>msg(e.message));

